keys:
  - &users:
    - &aftix age1q0n482cnaawz6kytqxge5gfc5u2rwll9vvgvc2tkw76kq4jvcghquyfhyc
  - &hosts
    - &hamilton age1xhq9q8h5k572mkulhnn9sl8k3xh22dzy5hjt67r48x5ctuvrwc8s7fveuw
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *aftix
      - *hamilton
