# SPDX-FileType: SOURCE
# SPDX-FileCopyrightText: (C) 2025 aftix
# SPDX-License-Identifier: EUPL-1.2

version = 1

[[annotations]]
path = "*"
SPDX-License-Identifier = "EUPL-1.2"
SPDX-FileCopyrightText = "(c) 2025 aftix"
