[display]
use_pager = true

[style.command_name]
foreground = "green"

[style.example_code]
foreground = "blue"

[style.example_variable]
foreground = "white"
underline = true

[updates]
auto_update = true
