theme = "ayu_dark"

[editor]
line-number = "relative"
auto-completion = true
auto-info = true
completion-trigger-len = 2
true-color = true
shell = ["zsh", "-cl"]
bufferline = "multiple"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "¬"
tabpad = "."

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-global = true
git-ignore = true
parents = true

[editor.lsp]
display-messages = true

[editor.search]
smart-case = true
wrap-around = false

[editor.indent-guides]
render = true
character = "|"
