name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-fermi:
    name: Deploy fermi NixOS server
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || !github.event.forced }}
    concurrency:
      group: deploy-fermi
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Create ssh key from repository secrets
        run: |
          install -m 600 -D /dev/stdin ~/.ssh/id_ed25519 <<< "${{ secrets.PRIVATE_KEY }}"
    
      - name: Add VPS fingerprint to known ssh hosts
        run: ssh-keyscan -H 170.130.165.174 > ~/.ssh/known_hosts

      - name: Deploy fermi
        run: >
          nix run 'github:serokell/deploy-rs' '.#fermi'

  iso:
    name: Create nixos isos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]
        variant:
          - minimal
          - graphical
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Generate ISO file
        run:
          nix run 'nixpkgs#just' iso "${{ matrix.variant }}" "${{ matrix.arch }}"
      - uses: actions/upload-artifact@v4
        with:
          name: nixos-aftix-${{ matrix.variant }}-${{ matrix.arch }}-linux.iso
          path: result/iso/*.iso
