name: check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: check nix flake
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
